from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MartialArtsAssets: 


	# Image Rule Assets
	# 武道大会活动主页标志（待裁模板） 
	I_MARTIAL_ARTS_MAIN = RuleImage(roi_front=(0,0,1,1), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/MartialArts/Martialarts/ma_martial_arts_main.png")
	# 武道大会战斗入口（待裁模板） 
	I_BATTLE_ENTRY = RuleImage(roi_front=(0,0,1,1), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/MartialArts/Martialarts/ma_battle_entry.png")


	# Image Rule Assets
	#  
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(996,552,45,49), roi_back=(996,552,45,49), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_battle_main_to_records.png")
	#  
	I_AP_UNLOCK = RuleImage(roi_front=(868,637,31,30), roi_back=(868,637,31,30), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_ap_unlock.png")
	#  
	I_MAR_FIRE_AP = RuleImage(roi_front=(1134,598,90,47), roi_back=(1134,598,90,47), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_mar_fire_ap.png")
	#  
	I_AP_LOCK = RuleImage(roi_front=(868,637,31,30), roi_back=(868,637,31,30), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_ap_lock.png")


	# Ocr Rule Assets
	#  
	O_AP_TICKET = RuleOcr(roi=(1138,19,83,27), area=(1138,19,83,27), mode="Single", method="Default", keyword="", name="ap_ticket")
	#  
	O_AP_COUNT = RuleOcr(roi=(941,18,83,27), area=(941,18,83,27), mode="Single", method="Default", keyword="", name="ap_count")


	# Image Rule Assets
	# 武道大会活动主页标志（待裁模板） 
	I_MAIN_GOTO_MAR = RuleImage(roi_front=(1190,380,37,39), roi_back=(1162,193,87,328), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_main_goto_mar.png")
	#  
	I_CHECK_MAIN_MAR = RuleImage(roi_front=(150,16,134,41), roi_back=(150,16,134,41), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_check_main_mar.png")
	#  
	I_TO_BATTLE_AP = RuleImage(roi_front=(905,227,26,131), roi_back=(905,227,26,131), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_to_battle_ap.png")
	#  
	I_TO_BATTLE_BOSS = RuleImage(roi_front=(1118,258,26,131), roi_back=(1118,258,26,131), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_to_battle_boss.png")
	#  
	I_CHECK_BATTLE_AP = RuleImage(roi_front=(150,16,134,41), roi_back=(150,16,134,41), threshold=0.8, method="Template matching", file="./tasks/MartialArts/mr/mr_check_battle_ap.png")


