from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class RichManAssets: 


	# Click Rule Assets
	#  
	C_RM_ROB_CHOICE_1 = RuleClick(roi_front=(155,436,100,100), roi_back=(155,436,100,100), name="rm_rob_choice_1")
	#  
	C_RM_ROB_CHOICE_2 = RuleClick(roi_front=(430,527,100,100), roi_back=(430,527,100,100), name="rm_rob_choice_2")
	#  
	C_RM_ROB_CHOICE_3 = RuleClick(roi_front=(727,526,100,100), roi_back=(727,526,100,100), name="rm_rob_choice_3")
	#  
	C_RM_ROB_CHOICE_4 = RuleClick(roi_front=(1015,369,100,100), roi_back=(1015,369,100,100), name="rm_rob_choice_4")


	# Image Rule Assets
	# 上锁图标 
	I_LOCK = RuleImage(roi_front=(886,646,31,30), roi_back=(871,620,69,76), threshold=0.7, method="Template matching", file="./tasks/RichMan/rm/as_lock.png")
	# 还未上锁图片 
	I_UNLOCK = RuleImage(roi_front=(886,646,31,30), roi_back=(871,620,69,76), threshold=0.7, method="Template matching", file="./tasks/RichMan/rm/as_unlock.png")
	# 活动爬塔标志 
	I_CLIMB_MODE_PASS = RuleImage(roi_front=(1141,544,21,21), roi_back=(1118,510,119,186), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_climb_mode_pass.png")
	# 活动通用挑战图标 
	I_ACT_FIRE = RuleImage(roi_front=(1132,602,84,45), roi_back=(1080,530,192,190), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_act_fire.png")


	# Image Rule Assets
	# 买门票 
	I_RM_BUY_TICKET = RuleImage(roi_front=(873,472,95,44), roi_back=(843,456,149,75), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_buy_ticket.png")
	# 买奖励 
	I_RM_BUY_REWARD = RuleImage(roi_front=(586,475,99,39), roi_back=(559,454,150,79), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_buy_reward.png")
	# 买体力 
	I_RM_BUY_AP = RuleImage(roi_front=(312,472,94,41), roi_back=(283,459,148,71), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_buy_ap.png")
	# 投掷骰子 
	I_RM_THROW = RuleImage(roi_front=(1139,604,70,43), roi_back=(1084,523,183,196), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_throw.png")
	# 投掷胜利 
	I_RM_THROW_WIN = RuleImage(roi_front=(667,317,65,80), roi_back=(608,261,189,186), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_throw_win.png")
	# 问答 
	I_RM_QUESTION = RuleImage(roi_front=(541,109,212,40), roi_back=(482,30,339,171), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_question.png")
	#  
	I_RM_FORWARD = RuleImage(roi_front=(550,495,91,43), roi_back=(515,474,161,100), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_forward.png")
	# 扔骰子平局 
	I_RM_THROW_EQUAL = RuleImage(roi_front=(350,355,51,75), roi_back=(277,307,189,186), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_throw_equal.png")
	#  
	I_RM_NO_TICKET = RuleImage(roi_front=(356,113,95,44), roi_back=(322,82,167,102), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_no_ticket.png")
	#  
	I_RM_MODE_ROB = RuleImage(roi_front=(486,28,306,32), roi_back=(465,16,349,54), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_mode_rob.png")
	#  
	I_RM_MODE_FIGHT = RuleImage(roi_front=(1132,600,95,44), roi_back=(1121,585,121,76), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_mode_fight.png")
	#  
	I_RM_FIGHT_UNLOCK = RuleImage(roi_front=(1132,510,32,32), roi_back=(1121,499,53,51), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_unlock.png")


	# Ocr Rule Assets
	#  
	O_RM_QUESTION = RuleOcr(roi=(358,159,593,111), area=(358,159,593,111), mode="Full", method="Default", keyword="", name="rm_question")
	#  
	O_RM_ANSWER_1 = RuleOcr(roi=(415,290,468,53), area=(415,290,468,53), mode="Single", method="Default", keyword="", name="rm_answer_1")
	#  
	O_RM_ANSWER_2 = RuleOcr(roi=(418,401,467,53), area=(418,401,467,53), mode="Single", method="Default", keyword="", name="rm_answer_2")
	#  
	O_RM_ANSWER_3 = RuleOcr(roi=(418,516,468,54), area=(418,516,468,54), mode="Single", method="Default", keyword="", name="rm_answer_3")


	# Image Rule Assets
	# 庭院进入活动 
	I_MAIN_GOTO_ACT = RuleImage(roi_front=(1188,228,35,28), roi_back=(1164,134,83,393), threshold=0.7, method="Template matching", file="./tasks/RichMan/rm/as_main_goto_act.png")
	# 右上跳过按钮 
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_skip_button.png")
	# 进入主要的战斗界面 
	I_TO_BATTLE_MAIN = RuleImage(roi_front=(1064,178,39,139), roi_back=(991,88,155,370), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_to_battle_main.png")
	# 从main进入到式神录 
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1015,560,39,42), roi_back=(674,539,439,157), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_battle_main_to_records.png")
	# 进入门票活动的按钮 
	I_AS_TO_PASS = RuleImage(roi_front=(624,505,38,35), roi_back=(273,141,759,475), threshold=0.65, method="Template matching", file="./tasks/RichMan/rm/as_as_to_pass.png")
	#  
	I_CHECK_RM_MAIN = RuleImage(roi_front=(148,13,174,47), roi_back=(121,0,227,72), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_check_rm_main.png")
	#  
	I_CHECK_RM_RICHMAN = RuleImage(roi_front=(148,13,140,47), roi_back=(121,0,227,72), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_check_rm_richman.png")


